# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.2.1
group=com.vaporvee.loadsupport
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Load Support
mod_author=vaporvee
mod_id=loadsupport
license=Apache License 2.0
credits=
description=Shows when the user has too less Java memory allocated, and plays a sound when the game has loaded.
minecraft_version_range=[1.21.1, 1.21.6)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Fabric
fabric_version=0.116.3+1.21.1
fabric_loader_version=0.16.10


# NeoForge
neoforge_version=21.1.184
neoforge_loader_version_range=[4,)

# Dependencies
cloth_version=15.0.140

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
